spring:
  datasource:
    url: jdbc:mysql://1.92.109.205:3306/chat_app?serverTimezone=UTC
    username: orlando
    password: Anchor_Mar25
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Shanghai

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect